### ISSUE TITLE
[BUG] Mobile: tables -  spacing below <a> text greater than plain text in table cells  

### ISSUE THREAD

**Issue by tblundell** [unimelb/design-system-issues#10]
## Expected behaviour
Consistent bottom spacing between the text and table cell (?)

## Current behaviour
On small screens, plain table text (not wrapped in `<p>`) has less space between text bottom and cell. (see screenshot below).

## Steps to reproduce

1. build table with text in a cell, and text wrapped in `<a>` in another
2. load page on mobile.

### Affected browsers

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] IE 11
- [ ] Safari 8+
- [x] iOS 8.4+
- [ ] Android 4.4+

## Possible solution

Screenshot taken from : https://lms.unimelb.edu.au/support/workshops/canvas

![IMG_F05EF3433402-1](https://user-images.githubusercontent.com/943446/68168722-dc36ee00-ffbd-11e9-9a7f-ee66ef3e0c9f.jpeg)

**Comment by tblundell** [comment]
Also, guessing the first header having top-border:0 is expected, but thought id mention in case the first child is meant to have a top border (not only bottom & sides).

**Comment by jaredh-um** [comment]
@makenosound couple of quirks on mobile here:

- [ ] Amend padding so it is consistent across cells - currently this selector is making those cells lose their bottom padding (not sure why they wanted that):

![Screen Shot 2019-11-05 at 1 37 12 pm](https://user-images.githubusercontent.com/34703139/68174402-18744980-ffd2-11e9-93f4-1f43c1848d37.png)

- [ ] Per Tim's second point around the header cell having no top border but still retaining side borders - this works better if the borders are dropped entirely for that cell

![Screen Shot 2019-11-05 at 1 40 47 pm](https://user-images.githubusercontent.com/34703139/68174459-51acb980-ffd2-11e9-9338-a49ec33d3e14.png)

Before:
![Screen Shot 2019-11-05 at 1 45 21 pm](https://user-images.githubusercontent.com/34703139/68174544-a2bcad80-ffd2-11e9-88c5-03ed3cc5454e.png)

After:

**Comment by tomstringer** [comment]
This one needs some more thinking. Those styling changes work ok on a simple table, but on more complex tables the lack of borders begins to get problematic.

See: https://web.unimelb.edu.au/components/tables/

![Screen Shot 2019-11-19 at 1 14 30 pm](https://user-images.githubusercontent.com/924501/69110352-93f3f180-0ace-11ea-9f94-5aa7f90550a1.png)

**Comment by jaredh-um** [comment]
@tomstringer I can't really see the CSS in full - are there breakpoint-specific properties for these tables? The issue raised was just for mobile; if the fixes can be scoped to that it might be fine?

**Comment by jaredh-um** [comment]
@tomstringer I've just re-applied the suggested fixes in the browser and it's working on mobile only there. I can't really suggest anything else here without seeing/understanding the full CSS (which is probably best left to an expert at this stage)
