### ISSUE TITLE
[BUG] Breadcrumb selector on mobile overflows 

### ISSUE THREAD

**Issue by rothenburycam** [unimelb/design-system-issues#11]
## Expected behaviour
On mobile, the page title in the breadcrumb selector should be contained with the select box.

## Current behaviour
On mobile, the page title in the breadcrumb selector overflows the select box.

## Steps to reproduce
https://mspace.unimelb.edu.au/courses/profession/community-services
![Screen Shot 2019-11-06 at 2 55 04 pm](https://user-images.githubusercontent.com/11714609/68267184-a79e6180-00a5-11ea-9d7b-09c85e69afd3.png)

### Affected browsers
- [X ] Chrome

## Possible solution
Change CSS style on `.uomcontent .page-header-navigation .mobile-nav .styled-select.alt select`

**Comment by jaredh-um** [comment]
Hi @makenosound, this looks like a similar issue to #75. I realise the chevron and line are pseudo elements, but is there some way of making that section of the select have a background colour (or put a margin-right on the select itself) to prevent the select text overlapping that area?

- [ ] Adjust styling to prevent select text entering dropdown chevron area
