### ISSUE TITLE
[BUG] Jumpnav anchors not easy to scan

### ISSUE THREAD

**Issue by catherinehunt** [unimelb/design-system-issues#13]
In the anchors of the Jumpnav, the text is now a bit larger than before and thus items are more likely to flow onto two lines. Also, the horizontal rules are gone. This makes the anchors much more difficult to scan through. They kind of blend into each other.

## Expected behaviour
Anchors that are easy to scan through (users need to be able to easily identify the beginning of each anchor)

## Current behaviour
As above

## Steps to reproduce
https://science.unimelb.edu.au/courses/frequently-asked-questions/choose-a-bachelor-of-science-major
https://science.unimelb.edu.au/courses/indigenous-students-in-science

### Affected browsers
- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] IE 11
- [ ] Safari 8+
- [ ] iOS 8.4+
- [ ] Android 4.4+

## Possible solution
A number of options possible - increase vertical space between anchors, reintroduce the horizontal rules, add a bullet character to the start of each anchor, indent turnovers...

**Comment by jaredh-um** [comment]
Hi @makenosound 

Can we please make the following adjustments:
- [ ] Remove bottom-margin set on `a` items (unless this is necessary for some reason)
- [ ] Add top and bottom padding to `li` items of around 8px/0.5rem
- [ ] Add bottom-border of Navy Mid 1 #ABBED5 to the `li` items

#### Previous

![Screen Shot 2019-11-12 at 2 33 09 pm](https://user-images.githubusercontent.com/34703139/68640171-03ac2e80-055b-11ea-85b4-0776ea87159c.png)

#### Current

![Screen Shot 2019-11-12 at 2 33 51 pm](https://user-images.githubusercontent.com/34703139/68640187-11fa4a80-055b-11ea-8663-918d7d503292.png)

#### Proposed

![Screen Shot 2019-11-12 at 2 39 12 pm](https://user-images.githubusercontent.com/34703139/68640209-1f173980-055b-11ea-8605-1ee801e7ba76.png)

**Comment by jaredh-um** [comment]
Duplicated in issue #21 (closed)
