### ISSUE TITLE
[BUG] Warning button isn't red enough

### ISSUE THREAD

**Issue by catherinehunt** [unimelb/design-system-issues#14]
The colour of the warning button is very tasteful and on-brand, but doesn’t really say ‘warning’ to me.  At least on my monitor, it displays as quite brown. Ditto for the "danger" notice class.

## Expected behaviour
Red-coloured button

## Current behaviour
Red-brown button (russet??)

## Steps to reproduce
`<a class="button warning">Warning</a>`

### Affected browsers
- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] IE 11
- [ ] Safari 8+
- [ ] iOS 8.4+
- [ ] Android 4.4+

**Comment by jaredh-um** [comment]
Hi @catherinehunt, you're spot on about the colour - it's actually the Orange Dark from our [digital colour palette](https://zeroheight.com/9jcq7n41q/v/draft/p/7641d0) as we don't have any reds! Was before my time so I can't explain the reasoning for that.

Anyway, I completely agree and I think for the sake of clarity that we can make an exception in this case. Top button pictured below uses an updated red.

![Screen Shot 2019-11-07 at 2 26 54 pm](https://user-images.githubusercontent.com/34703139/68358080-7c7e4580-016b-11ea-823a-22b8480e1ac8.png)

@makenosound this is probably the third time I've asked you to change this one, sorry

- [ ] Adjust warning button class to use red #DC291E
- [ ] Adjust danger notice class to use red background #DC291E

**Comment by tomstringer** [comment]
This one also needs a bit more attention. 

Red works ok on buttons, though the current hover state probably needs review (currently #984140).

Notices have both `warning` and `danger` classes: https://web.unimelb.edu.au/components/notices/

Red background on `danger` looks a bit hectic.

![Screen Shot 2019-11-19 at 1 24 33 pm](https://user-images.githubusercontent.com/924501/69110961-411b3980-0ad0-11ea-815b-53c5d8432fe2.png)

**Comment by jaredh-um** [comment]
@tomstringer cool, let's address the button itself here and I'll re-jig the notice ticket to resolve the other issues.
I've amended my comment above with an additional value for the hover background colour.
