### ISSUE TITLE
[BUG] Hero button on notice isn't readable

### ISSUE THREAD

**Issue by catherinehunt** [unimelb/design-system-issues#15]
When a hero button is placed on a notice, the text isn't readable, because it's a medium blue that doesn't have enough contrast with the button colour.

## Expected behaviour
Hero button has white text

## Current behaviour
Text is blue

## Steps to reproduce

![image](https://user-images.githubusercontent.com/33853991/68349152-41224d80-0150-11ea-9454-dced6d3dac8c.png)

There's an unpublished nested one of these on our home page: https://science.unimelb.edu.au/

### Affected browsers
- [ X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] IE 11
- [ ] Safari 8+
- [ ] iOS 8.4+
- [ ] Android 4.4+

**Comment by jaredh-um** [comment]
Hey @makenosound can you double check that this button class has it's own `color` set? Or is it being overidden by the notice component?

- [ ] Make button text visible when nested in notice component

**Comment by tomstringer** [comment]
@jaredh-um the hero-button currently has `background-color: color(var(--col-tertiary-navy) alpha(80%));`

Changing that to `background-color: transparent` is more in line with the Gen1 style, but in Gen3 the text color inherits.

![Screen Shot 2019-11-19 at 2 15 39 pm](https://user-images.githubusercontent.com/924501/69113567-78411900-0ad7-11ea-9d1e-31f0f137c30d.png)

The hover state for all of them is the same though: `background-color: rgba(3, 58, 123, 0.8);`

![Screen Shot 2019-11-19 at 2 22 59 pm](https://user-images.githubusercontent.com/924501/69113782-1b922e00-0ad8-11ea-871c-df8c7e691fa7.png)

**Comment by jaredh-um** [comment]
@tomstringer I'm reluctant to revert the hero button to the previous ['ghost'](https://uxplanet.org/ghost-buttons-in-ux-design-4cf3717334f8) styling as it's the least visible button when it's styled that why - and it's supposed to be a primary CTA, not a secondary.

We can address the text colour as one issue, but I think the requirement for an outline button probably still remains - but it shouldn't be the hero class. Is a 'soft' button an option in these cases? That's currently the only outline version remaining.

**Comment by jaredh-um** [comment]
The colour of the text on the buttons can be resolved by modifying the link colour selector for each of the 4 notice types. ie;
`.uomcontent [role="main"] .notice--success a`

needs to change to:
`.uomcontent [role="main"] .notice--success a:not(.button):not(.button-hero)`

This will prevent the buttons inheriting the `a` link colour that is otherwise set for each of the notice areas.

Hero buttons can be used here, but the 'soft' button class does not have enough contrast between the text and the background to work.
