### ISSUE TITLE
[BUG] MBS logo cut off

### ISSUE THREAD

**Issue by sprinsloo** [unimelb/design-system-issues#16]
The Melbourne Business School has a co-branded logo. The bottom section of the logo is being cut off in Gen3

## Expected behaviour
Logo to be displayed in full

## Current behaviour
Logo cut off
![Screen Shot 2019-11-07 at 12 52 40 pm](https://user-images.githubusercontent.com/4556924/68353394-8ef18280-015d-11ea-9376-8490835d553d.png)

## Steps to reproduce
See https://mbs.unimelb.edu.au/

### Affected browsers

- [x ] Chrome
- [x ] Firefox
- [ ] Edge
- [ ] IE 11
- [x ] Safari 8+
- [ ] iOS 8.4+
- [ ] Android 4.4+

**Comment by dkevey** [comment]
@tomstringer it looks like this one needs to be addressed in our cobranded overrides file. 
https://cms.unimelb.edu.au/central-site-management/template-assets/co-branded-logo/double-width-log-css.css

new width of 280px seems to work.
```
@media screen and (min-width: 768px)
.uomcontent .page-header a.page-header-logo {
    background-position: 0 -27px;
    width: 280px;
}
```
![image](https://user-images.githubusercontent.com/1305804/68354765-5a7fc580-0161-11ea-9c5a-b7d5b963b80d.png)

Also happening for https://asialink.unimelb.edu.au/_recache
- need to remove white line
![image](https://user-images.githubusercontent.com/1305804/68354896-c3ffd400-0161-11ea-8023-f24a72a6699c.png)

**Comment by sprinsloo** [comment]
We have a similar issue with the Melbourne Institute site where the identifier appears to be over the logo.
![Screen Shot 2019-11-07 at 1 25 02 pm](https://user-images.githubusercontent.com/4556924/68355005-0c1ef680-0162-11ea-97e7-e4e0b3961a66.png)

**Comment by dkevey** [comment]
```
.uomcontent .page-header.floating .page-header-home:before {content: none;} /*remove identifier white line as we're using logos instead */
.uomcontent .page-header a.page-header-logo {background-position: 0 -27px; width: 300px;}
```

**Comment by dkevey** [comment]
@sprinsloo do you know if Melbourne Institute has an approved logo for use on the new UoM blue background?  Looking for a better alternative than the white logo for the breadcrumbs. 

![image](https://user-images.githubusercontent.com/1305804/69024283-369c6980-0a16-11ea-90d6-45d69c8622f7.png)

also need an SVG version for MBS - the PNG version isn't very sharp. 
![image](https://user-images.githubusercontent.com/1305804/69024348-73686080-0a16-11ea-8584-8d58d7e1add2.png)

**Comment by tomstringer** [comment]
@jaredh-um Did we get anything further from the brand team about the dual lockup logos?

**Comment by jaredh-um** [comment]
Sent an email this morning asking for suitable versions of the following:
- MBS
- Melbourne Institute
- Asialink

I have the Bio21 logo on hand ready for export.

**Comment by jaredh-um** [comment]
MBS logos attached.

mbs_housed.svg - contains white background
mbs_reversed.svg  - contains no background, suitable for use on navy

[mbs_logos.zip](https://github.com/unimelb/design-system-issues/files/3913545/mbs_logos.zip)

**Comment by sprinsloo** [comment]
Sorry guys, I was away on annual leave. 

[UOM-MelbInstitute_SEC_RGB.ai.zip](https://github.com/unimelb/design-system-issues/files/3913682/UOM-MelbInstitute_SEC_RGB.ai.zip)

Here is the Illustrator file for the Melbourne Institute logo. We can replace the Uni logo with the correct uni-blue version. Let me know if you want me to update the file.

We don't look after AsiaLink, I think that sits with Arts.

**Comment by dkevey** [comment]
Hi @sprinsloo I've uploaded the new SVG logs can you please do a sanity check for me on mbs.unimelb.edu.au and let me know if logo looks ok? Thanks

**Comment by tomstringer** [comment]
Re-opening to track decoupling from the design switcher.

**Comment by sprinsloo** [comment]
@dkevey  the logos look good, thanks!

**Comment by tomstringer** [comment]
Updated so that the logo can be loaded depending on the design version being used.
