### ISSUE TITLE
[BUG] No space between blockquote and citation

### ISSUE THREAD

**Issue by venatiusj** [unimelb/design-system-issues#18]
## Expected behaviour
1) Needs equal spacing above and below the blockquote
2) Requires a space between the en dash and citation. 

## Current behaviour
1) No space between `<blockquote class="blockquote-classic">` and `<cite>`
2) No space between en dash (–) and citation.

## Steps to reproduce
Eg: https://mspace.unimelb.edu.au/#study-with-us
![image](https://user-images.githubusercontent.com/33737262/68564268-3ba46a80-04a4-11ea-947c-12e5f9bb3852.png)

### Affected browsers

- [ ✔ ] Chrome

**Comment by jaredh-um** [comment]
Hey @makenosound 

- [ ] For blockquote-classic, match the citation style of the standard blockquote

**Comment by tomstringer** [comment]
This change makes the two styles more-or-less indistinguishable. Not sure if that's the intention @jaredh-um?

![Screen Shot 2019-11-19 at 2 35 55 pm](https://user-images.githubusercontent.com/924501/69114592-facad800-0ad9-11ea-909d-482163b5ca89.png)

**Comment by jaredh-um** [comment]
The old ones are not aesthetically pleasing. We can revisit styling the 'new' variant at some stage but just thought I'd stick with something predictable for now.

![Screen Shot 2019-11-20 at 1 31 37 pm](https://user-images.githubusercontent.com/34703139/69204173-42b13400-0b9a-11ea-9e2a-56aef141cf78.png)

**Comment by tomstringer** [comment]
Some small changes have been made to these styles, but this is a bigger conversation that needs to happen as part of Gen 4. I'll move it back into the backlog.

**Comment by jaredh-um** [comment]
Closing this issue as Gen 4 will by necessity have its own blockquote styling where we can resolve some of these past issues.
