### ISSUE TITLE
[BUG] Pathfinders height is not consistent on tablet view

### ISSUE THREAD

**Issue by venatiusj** [unimelb/design-system-issues#19]
## Expected behaviour
On tablet view, height of the pathfinder boxes should be set equal to one that has the max content.

## Current behaviour
Height is inconsistent as it's dependent on text content on tablet view.

## Steps to reproduce
URL: https://online.unimelb.edu.au/#support
![image](https://user-images.githubusercontent.com/33737262/68564684-588d6d80-04a5-11ea-80f2-6df45a12acb2.png)

### Affected browsers
[✓] Tested on Chrome

**Comment by jaredh-um** [comment]
Should be addressed by issue #2.
