### ISSUE TITLE
[BUG] Pathfinder heading and text alignment

### ISSUE THREAD

**Issue by tblundell** [unimelb/design-system-issues#2]
## Is the feature request related to a problem? Please describe. 

Vertical alignment of all elements (header, text, buttons) is non-uniform. Makes for more effort to read/skim.

<img width="1354" alt="Screen Shot 2019-10-31 at 10 03 26 am" src="https://user-images.githubusercontent.com/943446/67905590-ffc8f580-fbc5-11e9-933f-6ad741212f69.png">

## Describe the solution you'd like 
Where all items are aligned. Also, all pathfinder boxes should ideally be the same v height (one of ours is a few px longer than the others -due to content).  

## Describe alternatives you've considered 
none.

## Additional context 
Additional screenshot demonstrating length issue (Ideally side items should stretch height of then centre).
<img width="1272" alt="Screen Shot 2019-10-31 at 10 10 12 am" src="https://user-images.githubusercontent.com/943446/67905803-bb8a2500-fbc6-11e9-9a09-48400a87f58f.png">

**Comment by tomstringer** [comment]
@tblundell Can you give us a URL for this one that we can take a look at?

**Comment by tblundell** [comment]
oops, sorry.
Top screenshot : https://lms.unimelb.edu.au/_recache#blackboard-lms
Second screenshot: https://lms.unimelb.edu.au/_recache#canvas-lms

**Comment by jaredh-um** [comment]
Looks like we need to change the heading font to more closely align with the behaviour of the original component.

@makenosound 

- [ ] Adjust heading font to be Source Sans Pro Bold, 1.25rem, standard text-transform
- [ ] Adjust height of heading section to be fixed and allow for up to three lines of heading text, vertically and horizontally centering the text within its section
- [ ] If this introduces too much white space for single line headings, consider re-adding a divider line
- [ ] Is there a way of removing the fixed height of the pathfinders and letting them be determined by the tallest content, with whitespace as appropriate in "shorter" pathfinders?
