### ISSUE TITLE
[BUG] Bold does not apply to `profilename` and `title` under "staff-listing-detailed"

### ISSUE THREAD

**Issue by venatiusj** [unimelb/design-system-issues#20]
## Expected behaviour
Profile name, title/address should have a different style from description.

## Current behaviour
There's no difference in text styles for `profile name`, `title` / `address` and profile description/blurb.

## Steps to reproduce
URL: https://online.unimelb.edu.au/#online-learning-experience
![image](https://user-images.githubusercontent.com/33737262/68565198-df8f1580-04a6-11ea-893b-458dbbd22167.png)

### Affected browsers
[✓] Chrome

**Comment by jaredh-um** [comment]
Hey @makenosound 

- [ ] Adjust `.uomcontent .staff-listing-detailed strong` to use `font-weight: 600` instead of `400`
