### ISSUE TITLE
[BUG] Link spacing on class="jump-navigation" should be greater. Too close together at the moment.

### ISSUE THREAD

**Issue by tonyz** [unimelb/design-system-issues#21]
## Expected behaviour
More spacing between each link

## Current behaviour
Looks and feels like one continuous link.

## Steps to reproduce
https://eng.unimelb.edu.au/engage/indigenous/views

### Affected browsers

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] IE 11
- [ ] Safari 8+
- [ ] iOS 8.4+
- [ ] Android 4.4+

**Comment by jaredh-um** [comment]
Hi @tonyz, this is being addressed in issue #13.
