### ISSUE TITLE
[BUG]Not really a bug... H2 suggestion

### ISSUE THREAD

**Issue by tonyz** [unimelb/design-system-issues#22]
## Expected behaviour
H2's currently have 'font-size: 2rem' styling.
Consideration for H2's to have 'font-size: 1.5rem' styling?

## Current behaviour
H2's currently have 'font-size: 2rem' styling

## Steps to reproduce
https://eng.unimelb.edu.au/engage/indigenous/views

### Affected browsers

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] IE 11
- [ ] Safari 8+
- [ ] iOS 8.4+
- [ ] Android 4.4+

**Comment by jaredh-um** [comment]
Hi @tonyz there is currently a ticket in to change the font family of the standard H2s to Source Sans Pro, which is visually more condensed than the current Noto Serif. 

#### Before

![Screenshot_2019-11-13 Victorian Indigenous Engineering Winter School](https://user-images.githubusercontent.com/34703139/68716166-b92cbf80-05f7-11ea-880c-6867274e0149.jpg)

#### After

![Screenshot_2019-11-13 Victorian Indigenous Engineering Winter School(2)](https://user-images.githubusercontent.com/34703139/68716189-c649ae80-05f7-11ea-856f-9f0bc058d801.jpg)
