### ISSUE TITLE
[Design] P text in headers uses too light a font weight

### ISSUE THREAD

**Issue by jaredh-um** [unimelb/design-system-issues#23]
#### Currently

Default `p` text in headers uses a light font weight, which makes the text somewhat difficult to read.

![weak p text in header to log.png](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/71a3eb12-729e-48b9-927d-4e50958356d2)

#### Proposed change

- [ ] Adjust `font-weight` on `.uomcontent [role="main"] > header:first-child p, .uomcontent [role="main"] header p` to `400`

**Comment by tomstringer** [comment]
This is a local style override on the MSPACE site. Removing the local style corrects it.

![Screen Shot 2019-11-19 at 2 42 54 pm](https://user-images.githubusercontent.com/924501/69114900-eaffc380-0ada-11ea-891f-b5a7d8e0f651.png)
