### ISSUE TITLE
[Design] Add padding by default to Page Listing CCT

### ISSUE THREAD

**Issue by jporich** [unimelb/design-system-issues#24]
![Screen Shot 2019-11-14 at 11 31 36 am](https://user-images.githubusercontent.com/10070570/68816743-6de7df00-06d3-11ea-86e0-dad9d5bcd946.png)

## Is the feature request related to a problem? Please describe. 
At present the Page Listing CCT doesn't insert extra padding on the top or bottom when viewed on the front end.

This means WYSIWYG sections making use of `<section>` to add padding are visually different to Page Listings which are "short" on the top and bottom. 

This exists in Gen 1 and Gen 3

## Describe the solution you'd like 
Add padding by default to the Page Listing CCT consistent with `<section>`s

## Describe alternatives you've considered 
Potentially adding a drop down to apply short vs. padded versions - however this will cause inconsistency with designs. Padding/margins should be added by default for design as it gives visual space to focus viewers eye on the content.

## Additional context 
This same issue appears to affect accordions

**Comment by dkevey** [comment]
Hi @jporich do you have some public URLS that we can look at please?

**Comment by jporich** [comment]
Cursory look through there's a difference depending on if a title is added or not:

(Page listing - _without_ title)

- Example 1: https://mdhs.unimelb.edu.au/engage/partners/_nocache#research-institutes

This page listing has a style attribute of `padding-top: 30px`. Compared to the previous tab (partners overview) where the section element has a `padding-top: 3rem;`

- Example 2: https://medicine.unimelb.edu.au/research/medical-research-themes 

Again - `padding-top: 30px` applied by way of style attribute on the Page Listing.

Appears this differs when a title is added 

(Page listing - _with_ title)

- Example 1: https://arts.unimelb.edu.au/engage/schools

Note: Page listing has no padding (Some weird artefacts, title is being added as attributes? Separate issues?)

Title has standard `<h2>` padding of `1.5rem`
------------------------------------------------------

Generally seems like inline style of `padding-top:30px` needs to be removed, and an embedded style of `padding: 3rem 0 3rem 0` should be added to the page listing class for top and bottom consistent padding in line with a `<section>`(?)

As well as this making any page listing titles have `padding-top: 0` to ensure there's no double up of page listing padding + title padding

**Comment by jaredh-um** [comment]
@dkevey is this a thing for you to address? Let me know if there's something Max might need to do

**Comment by dkevey** [comment]
Sorry I can't see what the issue is on those examples do you mind popping in some screenshots as well?

**Comment by jporich** [comment]
##Example 1
Note, attaching what users are doing as a workaround as the CCTs have insufficient padding

(Note: Issue is same in Gen 1 and Gen 3 - forgot to do as Gen 3 but hopefully you get the point)

![Screen Shot 2019-11-15 at 9 10 30 am](https://user-images.githubusercontent.com/10070570/68901149-80245480-0789-11ea-8b09-af2d6e663567.png)
![Screen Shot 2019-11-15 at 9 14 07 am](https://user-images.githubusercontent.com/10070570/68901176-861a3580-0789-11ea-9356-7a394ab9cd71.png)
![Screen Shot 2019-11-15 at 9 17 14 am](https://user-images.githubusercontent.com/10070570/68901184-8b778000-0789-11ea-88ff-8c30b58d9494.png)

##Example 2

![Screen Shot 2019-11-15 at 9 24 09 am](https://user-images.githubusercontent.com/10070570/68901432-0476d780-078a-11ea-9a53-178d091d15f3.png)
![Screen Shot 2019-11-15 at 9 26 19 am](https://user-images.githubusercontent.com/10070570/68901547-3a1bc080-078a-11ea-9dbc-e94154aab67b.png)

##example 3 (with title)
![Screen Shot 2019-11-15 at 9 28 13 am](https://user-images.githubusercontent.com/10070570/68901963-2cb30600-078b-11ea-9285-84b05dae6ebc.png)
![Screen Shot 2019-11-15 at 9 29 44 am](https://user-images.githubusercontent.com/10070570/68901969-2fadf680-078b-11ea-9f22-163337926e17.png)
![Screen Shot 2019-11-15 at 9 31 18 am](https://user-images.githubusercontent.com/10070570/68901976-32a8e700-078b-11ea-9d30-cc5d7f3d6d66.png)

**Comment by jporich** [comment]
# CCT padding after a Lead paragraph
Note:

In these examples - where CCT's follow a Lead paragraph of text I'm assuming that we want our CCTs to be consistent with other elements in our sites - as such any "block" following a lead paragraph should probably have 0 padding on top.

Take from https://arts.unimelb.edu.au/school-of-culture-and-communication#welcome

![Screen Shot 2019-11-15 at 9 43 44 am](https://user-images.githubusercontent.com/10070570/68902566-ce872280-078c-11ea-8292-21c264de1436.png)

**Comment by jporich** [comment]
@dkevey see above for screenshot examples of the differing padding between CCT variants.

**Comment by dkevey** [comment]
Hi @jporich thanks for sending through the examples. As far as we can see the issue exists in Gen 1 already and is quite complicated given mixed usage. We're going to tag this as something to tackle in Gen 4.

**Comment by jporich** [comment]
>Gen 4

😵 ⚰️ ✝️

**Comment by tomstringer** [comment]
Gen 4 just means any new stuff :-)

**Comment by dkevey** [comment]
Will add background and styling options - related to #34

**Comment by dkevey** [comment]
ok looks like #43 fixed this as well
https://cms.unimelb.edu.au/controlled-environment/law/melbourne-law-school-internships/_nocache#impact
