### ISSUE TITLE
[BUG] Blockquotes look bad

### ISSUE THREAD

**Issue by rothenburycam** [unimelb/design-system-issues#28]
Blockquote looks a bit weird - citation should be tightened up. Styling not very nice on the quote itself. 

## Expected behaviour
The citation should be tightened up and more nuances aesthetic treatment applied.

## Current behaviour
![Screen Shot 2019-11-15 at 3 44 56 pm](https://user-images.githubusercontent.com/11714609/68917560-f2635c00-07be-11ea-96b8-a15dd0f0fdce.png)

**Comment by tomstringer** [comment]
@rothenburycam Can you give us a link for this one? (Easier than us having to hunt down an example)

**Comment by jaredh-um** [comment]
@rothenburycam I think @venatiusj has beaten you to this one. Being addressed in issue #18

**Comment by venatiusj** [comment]
hi @jaredh-um thanks for actioning this. 

I just hard refreshed and tried again (Gen 3), it doesn't seem to be resolved:
https://mspace.unimelb.edu.au/#study-with-us

Should I be doing something differently?

**Comment by jaredh-um** [comment]
Sorry @venatiusj your original ticket is still in the backlog to be actioned

**Comment by venatiusj** [comment]
( ͡° ͜ʖ ͡°) @jared-um all good, thanks

**Comment by venatiusj** [comment]
( ͡° ͜ʖ ͡°)  @jaredh-um all good, thanks.
