### ISSUE TITLE
Buttons ">" to stick to last letter of button text 

### ISSUE THREAD

**Issue by tblundell** [unimelb/design-system-issues#3]
## Is the feature request related to a problem? Please describe. 
The ">" arrow inside buttons should ideally stay with the last letter/word of button text. Sometimes it drops to be orphaned, leaving the text on the line above, and the arrow below.   

## Describe the solution you'd like 
The ">" to never be an orphan.

## Describe alternatives you've considered 
nil

## Additional context 
Current arrow behaviour: 
![button](https://user-images.githubusercontent.com/943446/67906095-98ac4080-fbc7-11e9-927d-0a86707da565.png)

Non-orphaned ">"
<img width="196" alt="Screen Shot 2019-10-31 at 10 21 30 am" src="https://user-images.githubusercontent.com/943446/67906304-3e5faf80-fbc8-11e9-9cee-87dfa57a2720.png">

**Comment by jaredh-um** [comment]
@makenosound 
- [ ] Prevent `:after` pseudo element from wrapping by itself

**Comment by dkevey** [comment]
@jaredh-um @TimMansell @gepifanio Don't suppose you guys have a quick solution I can implement in CMS for this button where the arrow is dropping off - it's pretty ugly https://unimelb.edu.au/shop 
![Screen Shot 2020-03-19 at 8 34 25 am](https://user-images.githubusercontent.com/1305804/77009816-afa7cf80-69bc-11ea-991e-0346d03cf87d.png)

**Comment by dkevey** [comment]
temporally hiding the arrow on this page https://unimelb.edu.au/shop/_recache until we get a fix - looks much better I think

`.uomcontent [role=main] .pathfinder-2 a .button-small:after {display:none;}`

![Screen Shot 2020-03-19 at 9 11 09 am](https://user-images.githubusercontent.com/1305804/77012185-97867f00-69c1-11ea-81d0-eae53342911c.png)

**Comment by TimMansell** [comment]
Temp fix:

```
.uomcontent [role=main] .pathfinder-2 a .button-small {
  display: flex;
  align-items: baseline;
  white-space: nowrap;
}
```

**Comment by dkevey** [comment]
legend @TimMansell that looks great https://unimelb.edu.au/shop/_recache

**Comment by dkevey** [comment]
@tblundell I've added this as an override for now - it seems to be working, can you please check your pages and let me know? Thanks

**Comment by dkevey** [comment]
Had to tweak for mobile, all good now so closing this one off.
