### ISSUE TITLE
[BUG] "Article" Page Template headings have drop shadow even if there is no banner image set

### ISSUE THREAD

**Issue by jporich** [unimelb/design-system-issues#31]
## Expected behaviour
At the moment in Gen 1, if we have any pages making use of the "Article" Page Template - if there is no banner set there is a blue background (with white text).

In Gen 3 we would expect something similar (dark background, white text)

## Current behaviour
At present there is no background, and the text colour is blue - however there is still the presence of a drop shadow
![Screen Shot 2019-11-21 at 4 17 20 pm](https://user-images.githubusercontent.com/10070570/69306201-d5c19b00-0c7a-11ea-99c9-ae0d4d10477e.png)

## Steps to reproduce

1. Create page
2. Set page template to "Article"
3. Don't input a banner

## Possible solution
Detect when there is no banner set and ensure title doesn't have drop shadow (looks good without it!) Example:
![Screen Shot 2019-11-21 at 4 20 52 pm](https://user-images.githubusercontent.com/10070570/69306285-09042a00-0c7b-11ea-8232-76c17faf3b89.png)

Note: Currently on DEV site asset 3234772

Also Note: I think this is actually a massive improvement over the old Article default behaviour which was essentially an empty Hero Image. Looks nice and clean, and means we don't have to source good quality images for Article pages

**Comment by jaredh-um** [comment]
Hey Jimmy, definitely need to drop the drop shadow as it was only intended to help with legibility over images. Right now it's triggering memories of playing with the Eye Candy plugin in Photoshop in the 90s

- [ ] Amend one of the selectors below to have the property `text-shadow: none` to remove the shadow when there is no image used (possibly the second selector that has the color property?)

![Screen Shot 2019-11-22 at 10 47 43 am](https://user-images.githubusercontent.com/34703139/69386266-3651e600-0d16-11ea-86a9-ae2f0f46483f.png)

Result:

![Screen Shot 2019-11-22 at 10 53 19 am](https://user-images.githubusercontent.com/34703139/69386295-5386b480-0d16-11ea-92f0-4ce3e01b1664.png)
