### ISSUE TITLE
[QUESTION] Will circular aperture be applied to profile images?

### ISSUE THREAD

**Issue by rodley87** [unimelb/design-system-issues#32]
Example: [Scholarships](https://scholarships.unimelb.edu.au/)
Profiles listing at foot of page

**Current behaviour:**
![Screen Shot 2019-11-26 at 2 10 42 pm](https://user-images.githubusercontent.com/18609010/69596737-b8644680-1057-11ea-993d-5b966ec7e7fe.png)
Applied via this CSS:
```
border-radius: 50%;
    border-top-left-radius: 50%;
    border-top-right-radius: 50%;
    border-bottom-right-radius: 50%;
    border-bottom-left-radius: 50%;
```

**Gen3 behaviour:**
Image displayed as per its pixel dimensions, with no overlaying aperture
![Screen Shot 2019-11-26 at 2 23 15 pm](https://user-images.githubusercontent.com/18609010/69596928-67a11d80-1058-11ea-8403-b42748c8233a.png)

The same behaviour also occurs on [Student profile](https://scholarships.unimelb.edu.au/student-stories/professor-lyn-yates) and [donor](https://scholarships.unimelb.edu.au/donors/the-little-foundation) pages pages.

Personally, I prefer the square treatment. :wink:

Logging this as this is the only Gen3 issue I found, so nice work on a clean transition!!!

**Comment by jaredh-um** [comment]
Hi @rodley87, the circular treatment for profile photos has been deprecated as per previous Brand guidance 😄
