### ISSUE TITLE
Melbourne Institute - dual logo update

### ISSUE THREAD

**Issue by tomstringer** [unimelb/design-system-issues#35]

**Comment by jaredh-um** [comment]
Melbourne Institute logos attached.

melbourne_institute_reversed_tagline.svg - suitable for use on navy
melbourne_institute_reversed_no_tagline.svg - suitable for use on navy

[melbourne_institute_logos.zip](https://github.com/unimelb/design-system-issues/files/3913553/melbourne_institute_logos.zip)

**Comment by dkevey** [comment]
@jaredh-um the MI logos look incomplete, can you please double check. Should look like this: https://melbourneinstitute.unimelb.edu.au/__data/assets/image/0017/3230360/MelbInstitute-logo-8.png
these were what was in the ZIP file: 
https://melbourneinstitute.unimelb.edu.au/__data/assets/file/0007/3249619/melbourne_institute_reversed_tagline.svg
https://melbourneinstitute.unimelb.edu.au/__data/assets/file/0006/3249618/melbourne_institute_reversed_no_tagline.svg
https://melbourneinstitute.unimelb.edu.au/_recache

**Comment by jaredh-um** [comment]
@dkevey the background colour on those `a` sections is set to white. The logos I've provided above are the reversed ones that should be sitting on navy. Same issue is occurring in the breadcrumbs version

#### Currently with white bg
![Screen Shot 2019-12-09 at 1 07 50 pm](https://user-images.githubusercontent.com/34703139/70401718-fc5a4100-1a84-11ea-8819-7989f6d19716.png)

#### Should be
![Screen Shot 2019-12-09 at 1 08 12 pm](https://user-images.githubusercontent.com/34703139/70401740-09773000-1a85-11ea-80da-d33131f9ad2a.png)

**Comment by jaredh-um** [comment]
Hi @dkevey updated Melbourne Institute logo SVG attached - should match the appearance of the original, but in an inverted colourway

[melbourne_institute_reversed.svg.zip](https://github.com/unimelb/design-system-issues/files/3937763/melbourne_institute_reversed.svg.zip)

**Comment by dkevey** [comment]
MI logo has been added https://melbourneinstitute.unimelb.edu.au/_nocache

**Comment by tomstringer** [comment]
Reopening to decouple from design switcher

**Comment by tomstringer** [comment]
Updated so that the logo can be loaded depending on the design version being used.
