### ISSUE TITLE
Asialink - dual logo update

### ISSUE THREAD

**Issue by tomstringer** [unimelb/design-system-issues#36]

**Comment by jaredh-um** [comment]
Asialink reversed logo attached (co-branded version still TBC).

asialink_reversed.svg - suitable for use on navy

[asialink_logo.zip](https://github.com/unimelb/design-system-issues/files/3913556/asialink_logo.zip)

**Comment by tomstringer** [comment]
Reopening to track decoupling from design switcher.

**Comment by tomstringer** [comment]
Updated so that the logo can be loaded depending on the design version being used.
