### ISSUE TITLE
[BUG] <sup> doesn't have a size change when used with class="lead"

### ISSUE THREAD

**Issue by jporich** [unimelb/design-system-issues#38]
## Expected behaviour

font-size: 75% should be applied to all `<sup>` elements as used in uom.css for Gen 1 regardless of whether they are in body or lead or headings.

## Current behaviour

No sizing modification is made at all - leading to huge superscripts in lead text. `<sup>` is getting "font-size: 1.375rem;" applied

## Steps to reproduce

![screencapture-cms-unimelb-edu-au-controlled-environment-law-nocache-2019-12-03-09_12_07](https://user-images.githubusercontent.com/10070570/70000254-bbf35280-15ae-11ea-84b7-63bdd88c4180.png)

Only seen in dev site for law at the moment: https://cms.unimelb.edu.au/controlled-environment/law/

1. Insert a `<sup>` element in to a div that has a class of "lead" applied

### Affected browsers

Chrome, Firefox.

This is a CSS issue rather than a rendering issue

## Possible solution
Ensure that all `<sup>`'s regardless of position have font-size: 75% specifically applied

**Comment by tomstringer** [comment]
😳

Good pick up.
