### ISSUE TITLE
[BUG] No top padding on <h2 class="title"> if the CCT doesn't have .content-template (Pathfinder CCT identified)

### ISSUE THREAD

**Issue by jporich** [unimelb/design-system-issues#39]
## Expected behaviour

At present `<h2 class="title">` elements don't have any top-padding in CCTs that don't have `class="content-template"`

## Current behaviour

It appears top-padding has been removed across the board, and there's specifically a CSS rule for `.content-template h2.title { padding-top: 1.5rem; }` that's been created in gen 3. However weirdly it looks like the pathfinder CCT _doesn't_ have a class of "content-template" meaning this extra padding isn't applied.

Note: Works with Page Listing when a title is inserted - but Page Listing CCT has a class of "content-template" already.

## Steps to reproduce
![screencapture-cms-unimelb-edu-au-controlled-environment-law-nocache-2019-12-03-09_12_07](https://user-images.githubusercontent.com/10070570/70002051-11316300-15b3-11ea-89e1-3ad26d626d9c.png)

Example of CCT _with_ the class of `content-template` and making use of `<h2 class="title">`:
https://cms.unimelb.edu.au/controlled-environment/law/future/masters/

Example of CCT _without_ the class of `content-template` and making use of `<h2 class="title">`:
https://cms.unimelb.edu.au/controlled-environment/law/
 
1. Insert Pathfinder CCT
2. Set a title
3. Observe padding on front end

### Affected browsers
 
Chrome and Firefox

## Possible solution
Ensure all CCTs that have an option for a title have a class of "content-template" applied to them. At the moment I've only picked this up on the Pathfinder CCT so hopefully a one off - but wouldn't hurt to double check if we have the time

**Comment by jaredh-um** [comment]
Hey @jporich, we did indeed remove the padding from the generic H2s as it was the only heading type with top and bottom values applied.

@dkevey are you able to see if this is something that can be fixed within the Pathfinder CCT (by adding the `content-template` class) or do I need to propose a specific fix for this particular case?

**Comment by dkevey** [comment]
All the Content Templates need updating to use a better global JS/CSS file. I'll be adding in some additional styling options soon to help control this. Was going down the list - but will do Pathfinders and page listing as first priority.

**Comment by tomstringer** [comment]
@dkevey I've got another person reporting this one (same issue: `<h2 class="title">` in a pathfinder CCT). Is this something we'll have fixed before we release?

**Comment by dkevey** [comment]
Hey @jporich I've added in the custom `content-template` class to fix the `h2 class="title"` and adjusted to the class to have a `padding-top: 3rem` as `1.5rem` didn't look right, can you please test and confirm this issue is now resolved? thanks https://cms.unimelb.edu.au/controlled-environment/law/_recache
added in

**Comment by jporich** [comment]
Be-yyoooooo-di-ful.

Looks good @dkevey ! Thanks :)
