### ISSUE TITLE
[FEATURE] (possible duplicate) 'Filtered page listing' Page Template needs to sort by Asset Map - not alphabetical

### ISSUE THREAD

**Issue by jporich** [unimelb/design-system-issues#40]
Note: Appears I've been removed from previous repo's and can't seem to find original submission. Resubmitting here

## Is the feature request related to a problem? Please describe. 
At present, the [Filtered page listing](https://resources.web.unimelb.edu.au/controlled-environment/templates/special/filtered-list) Page template does not sort the third-level (individual page) by Asset Map position, but alphabetically.

This makes is very frustrating to give priority to pages. At present my solution is to add an alphabetised lettering to the beginning of each item:

![screencapture-cms-unimelb-edu-au-controlled-environment-law-current-study-options-nocache-2019-12-03-10_57_05](https://user-images.githubusercontent.com/10070570/70005306-332fe300-15bd-11ea-9086-97ffe0ac0f57.png)

e.g. This is even present on the example [implementation page](https://resources.web.unimelb.edu.au/controlled-environment/templates/special/filtered-list) - the ordering is incorrect!

"Child one", "Child three", "Child two" 

## Describe the solution you'd like 

Behaviour should mimic the 2nd-level pages and sort by asset map position. This allows far more control and for users to prioritise content.

This should be a simple enough switch on the Asset Listing page being used by the CCT to list out all these pages.

## Describe alternatives you've considered 

There could be an option for what sort of sort that we want to implement - however for consistency with all of our CCTs, it makes sense to make this sort by asset map position.

## Additional context 

Can be found in use with any standard Filtered List.

**Comment by dkevey** [comment]
@jporich I'm happy to make the change on this one, I'll just need to create some instructions/help guide on how to sort the child pages (for editors)

**Comment by jporich** [comment]
Ah fair enough - I get the feeling we have them somewhere...

Possibly @woowoowoo has some from Edit+ training on rearranging assets via the linking screen?

**Comment by dkevey** [comment]
@jporich the filtered listing has been updated to sort down the tree. 
have updated documentation here:
https://resources.web.unimelb.edu.au/controlled-environment/help-guides/how-to-use-a-filtered-listing-template

Have also created some reports to review page templates here: https://resources.web.unimelb.edu.au/controlled-environment/support/page-template-report
