### ISSUE TITLE
[BUG] Title text overlaps on Header with Box template

### ISSUE THREAD

**Issue by KarlS75** [unimelb/design-system-issues#41]
When the title test wraps to a second line in the Header with Box template, the words overlap making it difficult to read.  

## Expected behaviour

The two lines of text should appear with a space in between

## Current behaviour
The two lines of title text overlap

## Steps to reproduce

1.
![MCE3 0 Title bug - header with box template](https://user-images.githubusercontent.com/58237741/70012092-70996e00-15c7-11ea-92a1-04f064c3f828.png)

2.
![FF - MCE3 0 Title bug - header with box template](https://user-images.githubusercontent.com/58237741/70012297-282e8000-15c8-11ea-99ce-086ee9b105ca.png)

3.

### Affected browsers

- [y] Chrome
- [y] Firefox
- [ ] Edge
- [ ] IE 11
- [ ] Safari 8+
- [ ] iOS 8.4+
- [ ] Android 4.4+

**Comment by tomstringer** [comment]
@KarlS75 Can you give use a URL for this so we can have a closer look please?

**Comment by KarlS75** [comment]
Oh yes. Sorry about that!

https://education.unimelb.edu.au/mgse-industry-reports/report-1-those-who-disappear/report-child-pages/so-how-do-we-actually-lose-track-of-students

https://education.unimelb.edu.au/mgse-industry-reports/report-1-those-who-disappear/report-child-pages/dont-all-children-need-to-be-in-school-what-are-governments-doing-to-keep-young-people-in-education

Cheers, Karl

Karl Smith | Content and Communications Specialist
Melbourne Graduate School of Education
Ground floor, Kwong Lee Dow, 234 Queensberry Street
The University of Melbourne, Victoria 3010 Australia
T: +61 3 834 47108 M: +61 422 225 275 E: karl.smith@unimelb.edu.au<mailto:karl.smith@unimelb.edu.au>
education.unimelb.edu.au<http://education.unimelb.edu.au/> | facebook.com/mgseunimelb<https://www.facebook.com/mgseunimelb/> | twitter.com/EduMelb<https://twitter.com/EduMelb>


I acknowledge the Traditional Owners of the land on which I work, and pay my respects to the Elders, past and present.

[cid:image002.jpg@01D519FC.05B35730]

CRICOS: 00116K

This email and any attachments may contain personal information or information that is otherwise confidential or the subject of copyright. Any use, disclosure or copying of any part of it is prohibited. The University does not warrant that this email or any attachments are free from viruses or defects. Please check any attachments for viruses and defects before opening them. If this email is received in error, please delete it and notify us by return email.

**Comment by dkevey** [comment]
@jaredh-um `with-box` class has been added to the header - still needs font-size and line-height adjustment

And the header .box background used to be 80% opacity instead of 95% - not sure if this is correct?

https://resources.web.unimelb.edu.au/controlled-environment/templates/landing/header-with-box/_recache

https://education.unimelb.edu.au/mgse-industry-reports/report-1-those-who-disappear/report-child-pages/dont-all-children-need-to-be-in-school-what-are-governments-doing-to-keep-young-people-in-education/_recache
![image](https://user-images.githubusercontent.com/1305804/70015630-0fc36300-15d2-11ea-991d-7c6df18b89d5.png)

**Comment by jaredh-um** [comment]
Looks like we need a few fixes:

#### Fix the template
- [X] Add `with-box` class to `header` so H1 inside `box` can be targeted appropriately

#### Remove unnecessary properties
- Adjust the following properties on the `.uomcontent [role="main"] header .box h1` selector
- [ ] Remove `letter-spacing`
- [ ] Remove `line-height`
- [ ] Remove `margin-bottom`

#### Remove redundant font-size block
- [ ] Remove the following code block (no need to increase H1 at this breakpoint)

```
@media screen and (min-width:1099px) {
 .uomcontent [role=main]>header:first-child h1,
 .uomcontent [role=main] header h1 {
  font-size:3.4375rem;
  line-height:3.75rem
 }
}
```
#### Adjust header H1 font-sizes to bring in line with standard H1s
- [ ] Adjust the following code block to use standard H1 sizing at 769px+ (`font-size:2.625rem` and `line-height:3rem`)

```
@media screen and (min-width:769px) {
 .uomcontent [role=main]>header:first-child h1,
 .uomcontent [role=main] header h1 {
  font-size:2.8125rem;
  line-height:3.75rem;
 }
}
```

- [ ] Adjust the `.uomcontent [role="main"] > header:first-child h1, .uomcontent [role="main"] header h1` selector to use standard mobile H1 sizing (`font-size:2.25rem` and `line-height:2.25rem`)

**Comment by tomstringer** [comment]
I've also removed the padding from `.uomcontent [role="main"] header .box p` elements and added a top margin instead to compensate for the removal of `margin-bottom` from the `h1` element.

```
    p {
        font-size: pxtorem(18);
        line-height: 1.5;
        margin-top: pxtorem(24);
        font-weight: var(--fw-regular);
        padding: 0;
    }
```

**Comment by tomstringer** [comment]
@jaredh-um Do you want that opacity reduced as per @dkevey's comment? 

`.box { background: color(var(--col-white) alpha(95%));`

to

` .box { background: color(var(--col-white) alpha(80%));`

Or should we leave it as is?

**Comment by jaredh-um** [comment]
@tomstringer sorry, yeah you can change that back to the 80 as per @dkevey
