### ISSUE TITLE
[BUG] Tabbed nav <h2>'s all receiving margin-top (knock on effect from #43)

### ISSUE THREAD

**Issue by jporich** [unimelb/design-system-issues#44]
All `<h2>`'s receiving a top margin on pages that use Tabbed Navigation.

## Expected behaviour

Only the top-most `<h2>` should receive a margin-top of 3rem

`.uomcontent .tabbed-nav div:first-child h2 {
    margin-top: 3rem;
}`

## Current behaviour
All receiving margin-top
![Screen Shot 2019-12-04 at 3 42 41 pm](https://user-images.githubusercontent.com/10070570/70113491-7d908d00-16ad-11ea-9ade-006dca423a13.png)

https://law.unimelb.edu.au/study/masters/courses/specialist-certificate-in-law-digital-law-and-technological-innovation#apply-now

## Steps to reproduce

1. Go to a page utilising Tabbed Navigation
2. Insert several `<h2>`'s
3. notice margin on all items

### Affected browsers

Chrome, FF

## Possible solution

Seems to have resulted from fix in #43 

The CSS selector is currently:

`.uomcontent .tabbed-nav div:first-child h2`

Which is "for the .tabbed-nav class, any div's first-child that is a h2 do (x)"

That is, the `<div>`'s first child that is a `<h2>` is being selected (a lot) when it looks like what we want is to select any `<h2>`'s that immediately proceed after the beginning of a tab.

Basically we're trying to target any pages with a `<h2>` at the tippy-top of the page and add a bit of top-margin to it. 

Cases we should account for:

- User inserts a `<section>` and a `<h2>` immediately first
- User applies no "wrap" at all in the content container in squiz and there's a heading at the top
- User applies a `<div>` and a `<h2>` immediately after it

Soooooo we might end up with something more like 

.uomcontent .tabbed-nav .tab:first-child+[id^="content_container"]+h2, 
.uomcontent .tabbed-nav .tab:first-child+[id^="new_content_container"]+h2,
.uomcontent .tabbed-nav .tab:first-child+[id^="content_container"]+[id^="new_content_container"]+h2

Looks like gobbeldy-gook but it seems like we want to make use of the `+` selector to select "immediately proceeding items" to get to the first `<h2>` _if_ it exists at the top before any p's or other CCTs

**Comment by tomstringer** [comment]
😖 Nicely picked up. And good suggestions. Thanks @jporich

**Comment by dkevey** [comment]
thanks @jporich having a look at this one now

**Comment by jaredh-um** [comment]
Hey @jporich do your selectors account for the cases where the first div is nested in another div? Seems to be the case on a few of your tabs in that example

![Screen Shot 2019-12-05 at 8 49 40 am](https://user-images.githubusercontent.com/34703139/70184622-4cab6900-173c-11ea-8ef4-f2128bde7b59.png)

**Comment by dkevey** [comment]
I'm thinking that we don't target the H2 at all, and we should apply a class to the DIV wrapper instead. It would mean a bit of work editors (potentially) to apply the new class but this would be a better long term solution for stability and give control to editors.

**Comment by dkevey** [comment]
this is curious with multiple `DIV` and `SECTION` - is this done for testing purposes @jporich  or is this a mistake? Markup should be either `DIV` or `SECTION `not both

![image](https://user-images.githubusercontent.com/1305804/70187291-ec1f2a80-1741-11ea-8bb1-61df7c12e329.png)

**Comment by jporich** [comment]
The CSS is completely untested and almost certainly wrong :) better off with a FE dev investigating.

There's a looooot of different cases though, screenshot below for how these layers get made:

![Screen Shot 2019-12-05 at 8 58 10 am](https://user-images.githubusercontent.com/10070570/70188529-0e667780-1745-11ea-8c7e-f8de0522ee37.png)

- In regards to the "many divs" it's a result of many nested containers.
- I've always thought we should just have a default top+bottom padding and then target the top-most and bottom-most containers to remove their paddings to zero 

Very tricky as there's a lot of layering and variability depending on what the user inserts or nests.

E.g. If you view the asset ID's of those divs @dkevey you can see they're a result of using tabbed nav _and then_ nesting another page (which has it's own divs and stuff)

**Comment by dkevey** [comment]
yeah the combination of tabbed nav content really does my head in. Tim and I just had a look and we think the best way handle this is to apply a class to the `DIV` on a content containers i.e `content-block` or `content-block content-block--short` with the option of `alt` for a grey background so that editors have control of the final output.  

@jporich could you please do some testing for me to see if this would work in the above scenario? I'm working on some documentation here: https://resources.web.unimelb.edu.au/controlled-environment/styling-content/content-blocks

Changing the padding-top on the H2 is like ripping a band-aid off and I don't really want to put another one on it.

**Comment by jporich** [comment]
Might be a bit with testing sorry @dkevey - I'll add it to my to-do's but a bit under the pump at the moment between Canvas rollout, new LMS Learning Designer hired, and fixing our existing issues before the Gen 3 rollout :( 

Might not be able to test it in time for rollout

**Comment by tomstringer** [comment]
Looks pretty good to me. I'll leave this one open until @jporich can have a go at it, but should be good to go.
