### ISSUE TITLE
[Design] In-page navigation design tweaks

### ISSUE THREAD

**Issue by jaredh-um** [unimelb/design-system-issues#46]
### Currently

There are two layouts for the in-page navigation component - fixed (sidebar) and table of contents.

**Fixed:**
![Screen Shot 2019-12-06 at 2.42.14 pm.png](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/24f36ad5-9194-4ea1-bea9-d9cd9f8dc03a)

**Table of contents:**
![Screen Shot 2019-12-06 at 2.42.05 pm.png](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/565c7624-5d8b-4270-831f-eeb0aee55252)

### Proposed changes
I hadn't come across the table of contents version until I noticed it on the [Buttons page](https://unimelb-design-system-icelab.herokuapp.com/components/buttons). It looks a bit liney so I'm proposing a few changes to bring the two layouts into line:

**Both versions:**
- [ ] Remove identifier line pseudo-elements

**Fixed version:**
- [ ] Remove `border-bottom` from first `li` item ("On this page") or set it to none

![Screen Shot 2019-12-06 at 2.51.30 pm.png](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/f07db588-1331-4571-a5a1-8cf0e3bb4087)

**Table of contents version:**
- [ ] Retain `border-bottom` on first `li` item only

![Screen Shot 2019-12-06 at 2.40.54 pm.png](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/a458bb3c-87c5-4060-bf8a-0b468d149912)

**Comment by makenosound** [comment]
I’ve made these change in https://github.com/unimelb/Gen3/pull/173

**Comment by jaredh-um** [comment]
Hey @makenosound this looks like it's mostly done - there's just some remnants existing at the 1099px+ breakpoint which revert the table of contents style version to a weird display (seen [here](https://unimelb-design-system-icelab.herokuapp.com/components/buttons)):

![Screen Shot 2019-12-09 at 11 54 44 am](https://user-images.githubusercontent.com/34703139/70399738-c617c400-1a7a-11ea-9e68-5488608dd9c8.png)

![Screen Shot 2019-12-09 at 11 52 08 am](https://user-images.githubusercontent.com/34703139/70399744-cc0da500-1a7a-11ea-84ae-e40781f18024.png)

Can we get rid of these groups? They appear to be for stylistic changes at 1099px+ that we probably don't need anymore?

**Comment by makenosound** [comment]
@jaredh-um Nice pick up, I didn’t realise there were two different incarnations of that element either (separate from their appearance on different screen sizes). Should be resolved now.
