### ISSUE TITLE
[BUG] Headings used in custom site footer appear blue on a blue background

### ISSUE THREAD

**Issue by nmiller-unimelb** [unimelb/design-system-issues#5]
All Gen 3 headings are a navy blue colour. This is normally fine, but when used in a custom site footer they appear navy blue on a royal blue background (see attached screenshot from the students.unimelb development site). This looks a bit funny.
I could style the individual headings to make the text white, but it might be better to update the CSS classes so that headings in a footer appear white?
<img width="1243" alt="Screen Shot 2019-10-31 at 10 37 05 am" src="https://user-images.githubusercontent.com/24399570/67907123-fd1ccf00-fbca-11e9-8725-803d3eb360a6.png">

**Comment by tomstringer** [comment]
@nmiller-unimelb Can you give us a URL for this one please?

**Comment by nmiller-unimelb** [comment]
Apologies @tomstringer - https://cms.unimelb.edu.au/controlled-environment/students

**Comment by jaredh-um** [comment]
@makenosound 

The Gen 1 design system doesn't seem to have any general provision to invert text colours when certain backgrounds are used.

- [ ] Add a `color` property to a broad heading selector to change headings to white when the `cta` class is used (as this has the background colour)

**Comment by makenosound** [comment]
I’ve fixed this in https://github.com/unimelb/Gen3/pull/173 and merged that so it should be visible in prod now.

**Comment by tomstringer** [comment]
Looks good @makenosound - thanks.

@nmiller-unimelb you can remove the hardcoded CSS from that element now. Should work fine.
