### ISSUE TITLE
[BUG] Figure Floating content container needs a way to add padding

### ISSUE THREAD

**Issue by catherinehunt** [unimelb/design-system-issues#50]
Unless I'm missing something, there's no way to give the Figure Floating content container some more padding. For example, see here: https://science.unimelb.edu.au/students/bsc-orientation#getting-to-campus. I tried wrapping it in a content-block div and section tags, but no dice. Thanks.

## Expected behaviour
Wrapping the container in the content-block div should create padding above.

## Current behaviour
Content too close to previous.

## Steps to reproduce
https://science.unimelb.edu.au/students/bsc-orientation#getting-to-campus

**Comment by dkevey** [comment]
Will tackle this one next to add in some styling options as per accordion and page listing

**Comment by dkevey** [comment]
Template has been updated see news item: https://resources.web.unimelb.edu.au/controlled-environment/news/figures-floating
