### ISSUE TITLE
[Design] Breadcrumbs design treatment with megamenu needs attention

### ISSUE THREAD

**Issue by tomstringer** [unimelb/design-system-issues#55]
Gen 4 breadcrumbs were introduced to show with the mega-menu implementation, but the design treatment creates some awkward visuals - particularly where the blue header is used (see Nick's email below).

We need a more considered design treatment for how the breadcrumbs render when the megamenu is used.

> From: Nick Miller <nicholas.miller@unimelb.edu.au>
> Date: Friday, 31 January 2020 at 11:30 am
> To: Jared Henderson <jared.henderson@unimelb.edu.au>, Tom Stringer <t.stringer@unimelb.edu.au>, Rachid Annab <rannab@unimelb.edu.au>, Anthony Mannering <anthony.mannering@unimelb.edu.au>
> Cc: Sebastian Cortes <sebastian.cortes@unimelb.edu.au>, Nathan Dorey <nathan.dorey@unimelb.edu.au>
> Subject: Breadcrumb design issues
> 
> Hi DOC team,
>  
> After a bit of consideration about the mega-menu/breadcrumb combo in Gen 3, I wanted to let you know about the issues we’ve noticed and our proposed fixes.
>  
> We feel that the appearance of the breadcrumbs when used on the default page template of ‘Inside page with blue header’ is not good. It creates a striped effect, with one white bar sandwiched in-between two blue ones (see screenshot 1, attached). 
>  
> Switching page templates to ‘Inside page with no header’ fixes this issue. However, the vertical line to the right of the jump nav butts up against the breadcrumbs (see screenshot 2).
>  
> We appreciate that these are aesthetic issues rather than functional ones, but they do impact the user-experience of the site.
>  
> After a bit of discussion and experimentation, we think the easiest way to solve these issues would be to adjust the breadcrumb CSS as follows:
>  
> On page templates which have a blue header or a graphic banner (e.g. Inside page with header, Header with image (light))
>  
> •	Change the breadcrumb background colour to #012a58 (the same background colour as the header)
> •	Change the breadcrumb font colour to #fff (the same colour as the H1 text)
> •	Decrease the breadcrumb font size to 0.9em. They are currently using a similar font size to the mega-menu, which we think overemphasises their importance a little.
>  
> Please see screenshots 3 and 4 attached for some mock-ups of how this would look.
>  
> On the inside page with no header template
>  
> •	Add 10px or so of extra padding to the bottom of the breadcrumbs to create some space between breadcrumb and jump nav
> •	Decrease the breadcrumb font size to 0.9em (as above).
>  
> Could you please review and let us know whether you think this type of change would be possible to make? If not we may consider adding some site-wide CSS in the short-term to improve the look and feel.
>  
> Regards,
> Nick
> 
>
> 
> ![Screenshot 4](https://user-images.githubusercontent.com/924501/73796585-b52cca00-4801-11ea-94a4-662012114912.png)
> ![Screenshot 3](https://user-images.githubusercontent.com/924501/73796590-b78f2400-4801-11ea-9462-f5f184d9d12e.png)
> ![Screenshot 2](https://user-images.githubusercontent.com/924501/73796591-b827ba80-4801-11ea-93d0-6e45f1913140.png)
> ![Screenshot 1](https://user-images.githubusercontent.com/924501/73796592-b8c05100-4801-11ea-87a5-d9ccff304a75.png)

**Comment by tomstringer** [comment]
Issue moved to [unimelb/Gen4 #10](https://github.com/unimelb/Gen4/issues/10) via [**ZenHub**](https://www.zenhub.com/)

**Comment by tomstringer** [comment]
Didn't mean to do that, soz.

**Comment by jaredh-um** [comment]
Interim changes as discussed with Donna to be implemented and tested:

![Screen Shot 2020-03-13 at 11 57 39 am](https://user-images.githubusercontent.com/34703139/76581693-6c66e000-6528-11ea-8337-3dea0e88cd81.png)

**Comment by dkevey** [comment]
@nmiller-unimelb I'm testing changes to breadcrumbs on our site here if you want to have a look and let me know what you think:
- [header with image](https://resources.web.unimelb.edu.au/controlled-environment/templates/landing/header-with-image)
- [inside with blue header](https://resources.web.unimelb.edu.au/controlled-environment/templates/standard/inside-page-with-blue-header) and [with jump nav](https://resources.web.unimelb.edu.au/controlled-environment/templates/standard/inside-page-with-blue-header/inside-page-with-jump-nav)
- [inside page no header](https://resources.web.unimelb.edu.au/controlled-environment/templates/standard/inside-page-with-no-header) and [with jump nav](https://resources.web.unimelb.edu.au/controlled-environment/templates/standard/inside-page-with-no-header/with-jump-nav)

**Comment by nmiller-unimelb** [comment]
Thanks @dkevey - will take a look and get back to you on Monday.

**Comment by nmiller-unimelb** [comment]
Hi @dkevey ,

Thanks for the opportunity to review this, I think it looks good and is a definite improvement on the current state.

A couple of questions (possibly more for @jaredh-um ):

- I notice that the background colour of the header bar has also been changed. Did you feel that this was required to visually seperate the breadcrumbs from the header? Our original preference was to have the breadcrumb and header bars the same colour (#012a58), but this is not a big deal.
- On mobile, the breadcrumb only displays the home icon and the current page. We were wondering if it might be more useful for the breadcrumb to show the page immediately above, rather than the current page? But also understand this is a further change which may require additional thought and research.

Aside from that, we’re happy with the changes and ready for them to be rolled out. Thanks again :-) 

Nick

**Comment by dkevey** [comment]
@nmiller-unimelb yeah - RE: breadcrumbs colour - yes we thought it looked weird with the breadcrumbs bleeding into the header background colour. After having a break from the breadcrumbs and looking at it fresh today - I actually don't like the dark blue breadcrumbs. Will chat with @jaredh-um again. 

Also the issue of breadcrumbs on mobile seems to be happening on the current design - I'm not sure that's something I can change, and would be better to submit in a seperate ticket I think (sorry we're short of FE developers right now)

**Comment by nmiller-unimelb** [comment]
Thanks @dkevey.

Re: the breadcrumbs background colour, my only other feedback would be that having different colours/shades for the menu, breadcrumbs and header means there's still a bit of a 'striped' effect going on - albeit one that looks a lot better than the blue/white/blue effect we have at the moment. Anything which helps those three segments at the top of the page to look more cohesive would be great.

**Comment by jaredh-um** [comment]
@nmiller-unimelb @dkevey I'll look into this again.

**Comment by jaredh-um** [comment]
So I've looked at this for a while, and for an interim fix I think Nick's original suggestions are probably the most viable - regardless of colour, if the plain header background is different to the breadcrumbs then we're going to get a striped effect.

**Comment by dkevey** [comment]
Yeah I think so too @jaredh-um I saw a couple other sites doing something similar i.e.
https://www.anz.com.au/personal/bank-accounts/ 
https://www.anz.com.au/personal/bank-accounts/everyday-accounts/access-advantage/

Will revert that change back and roll out tomorrow

**Comment by dkevey** [comment]
Have implemented this change in CMS so I'll close this ticket off
