### ISSUE TITLE
[BUG] font of citation class

### ISSUE THREAD

**Issue by dcollett** [unimelb/design-system-issues#59]
The font for the citation class has changed. It's currently the default Roboto font - previously was Courier. This appears to have changed with the recent design system updates

## Expected behaviour
The font for the citation class would still be Courier

## Current behaviour
The font for the citation class is Roboto

## Steps to reproduce
Old design system example = https://web.unimelb.edu.au/components/text/#citation
New design system example = https://academicintegrity.unimelb.edu.au/forms-of-plagiarism/mosaic-copyingscaffolding

### Affected browsers

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] IE 11
- [x] Safari 8+
- [x] iOS 8.4+
- [ ] Android 4.4+

## Possible solution
Citation class font-family = Courier New,Courier,fixed

**Comment by dkevey** [comment]
Hi @jaredh-um  are you happy for this change:
**CURRENT** Citation
![Screen Shot 2020-07-31 at 1 34 29 pm](https://user-images.githubusercontent.com/1305804/88997276-ac412f00-d332-11ea-9d5f-f2435ec85662.png)

**PROPOSED CHANGES** 
![Screen Shot 2020-07-31 at 1 32 13 pm](https://user-images.githubusercontent.com/1305804/88997205-78660980-d332-11ea-9823-8f2f367fb05a.png)

**PREVIOUS citation**
![Screen Shot 2020-07-31 at 1 32 43 pm](https://user-images.githubusercontent.com/1305804/88997190-70a66500-d332-11ea-99d8-819b08e139fa.png)

**Comment by jaredh-um** [comment]
@dkevey That looks totally fine; can I ask where you got the `font-family` set from? I've just checked Gen 2 and we don't appear to have a defined set for monospaced fonts there, so it might be worth settling on an official list.

**Comment by dkevey** [comment]
@jaredh-um in **Gen 3** it's defined in the **_globals.css** file as  
`--ff-fixed: SFMono-Regular, Consolas, Liberation Mono, Menlo, Courier, monospace;`

**Comment by jaredh-um** [comment]
Sure, makes sense to stick with that.
