### ISSUE TITLE
[BUG] Large homepage banners have faint horizontal line through them

### ISSUE THREAD

**Issue by nmiller-unimelb** [unimelb/design-system-issues#6]
In Gen 3, large homepage banner images appear to have a faint horizontal line through them (see attached screenshots of careers.unimelb.edu.au in Gen 1 vs Gen 3 for example of this).
<img width="1435" alt="Screen Shot 2019-10-31 at 10 48 43 am" src="https://user-images.githubusercontent.com/24399570/67907540-4de0f780-fbcc-11e9-9761-41b77a4a92f1.png">
<img width="1434" alt="Screen Shot 2019-10-31 at 10 49 01 am" src="https://user-images.githubusercontent.com/24399570/67907542-4e798e00-fbcc-11e9-9e36-ccc8c211c4f7.png">

**Comment by jaredh-um** [comment]
Will be addressed by tickets #84 and #95
