### ISSUE TITLE
[BUG] Hamburger icon still displays when no local menu is selected

### ISSUE THREAD

**Issue by dkevey** [unimelb/design-system-issues#60]
In Gen 1 the local hamburger menu could be [disabled](https://resources.web.unimelb.edu.au/controlled-environment/help-guides/managing-your-local-site-menu) by editors (handy if the site is small and not required). However the icon was still present due to the global IA being injected via javascript.

In Gen 3 the global IA was moved into the footer, so now if the local menu is disabled, the icon is still visible and overlay is visible when clicked. 

See example showing Gen1 vs Gen 3: https://www.screencast.com/t/XOVwRmyqC2y

Need a solution if local menu is disabled the hamburger icon is not printed. 

Example site: https://www.unimelb.edu.au/cybersecurity

**Comment by jaredh-um** [comment]
Hey @dkevey, has this one been resolved? Can't check the video but visiting the page example, it looks like the hamburger menu is gone... or maybe that was an override just done for this page?

**Comment by dkevey** [comment]
@jaredh-um @gepifanio I can't replicate either. Perhaps close this issue for now.
