### ISSUE TITLE
[BUG] Horizontal scroll when header not collapsed

### ISSUE THREAD

**Issue by tblundell** [unimelb/design-system-issues#9]
I just noticed one of our pages (eg: https://le.unimelb.edu.au/news/articles/learning-and-teaching-initiative-lti-grants-2020) sometimes allows you to scroll left. 
Ive only checked in safari.

NOTE: I've noticed the behaviour on a page containing the left nav injection - ON THIS PAGE - (content anchors), although the links remain fixed.  

![left-scroll-issue](https://user-images.githubusercontent.com/943446/67918997-be027400-fbf2-11e9-97dd-f1d98168fdf3.gif)

## Expected behaviour

No horisontal scrolling, only vertical.

## Current behaviour

You should be able to see by this animated gif (if it remains a gif!) that at the top of the page, the whole page can scroll left leaving a white margin on the right. After the header turns to the slim version this behaviour isn't happening.

## Steps to reproduce

1. Load page and do not scroll down
2. drag fingers (or move mouse wheel) left to right inside the browser window. 
3. scroll down and try the same left/right motion, the page should not move
4. scroll up again, and wait one to two seconds before repeating left/right motion.  

### Affected browsers

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] IE 11
- [x] Safari 8+
- [ ] iOS 8.4+
- [ ] Android 4.4+

## Possible solution
css fix.

**Comment by jaredh-um** [comment]
@makenosound there appears to be an issue with the way the width is set on the Breadcrumbs.

![Screen Shot 2019-11-05 at 11 25 17 am](https://user-images.githubusercontent.com/34703139/68169085-04731c80-ffbf-11e9-8766-804c1620f6b6.png)

Removing the following resolves the immediate issue:
![Screen Shot 2019-11-05 at 11 23 39 am](https://user-images.githubusercontent.com/34703139/68169096-0d63ee00-ffbf-11e9-9151-ca51f96889d8.png)

- [ ] Adjust breadcrumbs so width is contained within parent elements

**Comment by makenosound** [comment]
Should be fixed in https://github.com/unimelb/Gen3/pull/173 and live.

**Comment by jaredh-um** [comment]
Hey @makenosound it looks like there's a horizontal scroll happening on the menu header now. Visible on:
https://le.unimelb.edu.au/news/articles/learning-and-teaching-initiative-lti-grants-2020/_recache
https://unimelb-design-system-icelab.herokuapp.com/components/buttons

![Screen Shot 2019-12-09 at 10 50 35 am](https://user-images.githubusercontent.com/34703139/70398644-c364a100-1a71-11ea-8910-02276e5eb424.png)

**Comment by makenosound** [comment]
Ah, yep, this should be fixed now.

**Comment by tomstringer** [comment]
Looks good.
